version: 2
jobs:
  build:
    working_directory: ~/miniflix
    docker:
      - image: node:8.1.3-alpine
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'yarn global add npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
