version: 2
jobs:
  build:
    working_directory: ~/react-authentication
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test

      - setup_remote_docker

      - checkout
      - run:
          name: build docker image
          command: |
            docker build --rm=false -t registry.heroku.com/thawing-hollows-45878/web .
      - run:
          name: Push to Heroku
          command: |
            docker login -u $HEROKU_LOGIN -p $HEROKU_API_KEY registry.heroku.com
            docker push registry.heroku.com/thawing-hollows-45878/web
